<script setup>
import { onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { auditRiderApplication, auditRiderInfoChangeRequest, auditRiderWithdrawal, listRiderApplications, listRiderInfoChangeRequests, listRiderWithdrawals } from '../../api/admin'
const applications = ref([]); const withdrawals = ref([]); const infoChanges = ref([]); const loading = ref(false)
async function load(){loading.value=true;try{[applications.value,withdrawals.value,infoChanges.value]=await Promise.all([listRiderApplications(),listRiderWithdrawals(),listRiderInfoChangeRequests()])}finally{loading.value=false}}
async function auditApplication(item,decision){await auditRiderApplication(item.id,{decision,reason:decision==='APPROVE'?'审核通过':'资料不符合要求',maxActiveOrders:3});ElMessage.success('已处理');load()}
async function auditWithdrawal(item,approved){await auditRiderWithdrawal(item.id,{approved,reason:approved?'审核通过':'审核驳回'});ElMessage.success('已处理');load()}
async function auditInfoChange(item,approved){let reason='资料核验通过';if(!approved){try{const result=await ElMessageBox.prompt('请填写驳回原因，将展示给骑手。','驳回联系电话修改',{inputPattern:/.+/,inputErrorMessage:'请填写驳回原因'});reason=result.value}catch{return}}await auditRiderInfoChangeRequest(item.id,{approved,reason});ElMessage.success('资料修改审核已完成');load()}
onMounted(load)
</script>
<template><section v-loading="loading"><h1>骑手运营</h1><el-card><template #header>骑手申请</template><el-table :data="applications"><el-table-column prop="realName" label="姓名"/><el-table-column prop="vehicleType" label="车辆"/><el-table-column prop="serviceArea" label="服务区域"/><el-table-column label="操作"><template #default="{row}"><el-button size="small" type="success" @click="auditApplication(row,'APPROVE')">通过</el-button><el-button size="small" type="danger" @click="auditApplication(row,'REJECT')">驳回</el-button></template></el-table-column></el-table></el-card><el-card class="section"><template #header>服务联系电话修改</template><el-table :data="infoChanges" empty-text="暂无待审核的资料修改"><el-table-column prop="riderId" label="骑手账号"/><el-table-column prop="currentPhone" label="当前号码"/><el-table-column prop="requestedPhone" label="申请号码"/><el-table-column prop="createdAt" label="申请时间" min-width="170"/><el-table-column label="操作" width="180"><template #default="{row}"><el-button size="small" type="success" @click="auditInfoChange(row,true)">通过</el-button><el-button size="small" type="danger" @click="auditInfoChange(row,false)">驳回</el-button></template></el-table-column></el-table></el-card><el-card class="section"><template #header>提现审核</template><el-table :data="withdrawals"><el-table-column prop="riderId" label="骑手"/><el-table-column prop="amount" label="金额（分）"/><el-table-column prop="status" label="状态"/><el-table-column label="操作"><template #default="{row}"><el-button size="small" type="success" @click="auditWithdrawal(row,true)">批准</el-button><el-button size="small" type="danger" @click="auditWithdrawal(row,false)">驳回</el-button></template></el-table-column></el-table></el-card></section></template><style scoped>.section{margin-top:20px}</style>
