import { api, unwrap } from './client'

export const listAvailableRiderOrders = () => api.get('/rider/orders/available').then(unwrap)
export const listMyRiderOrders = () => api.get('/rider/orders/me').then(unwrap)
export const claimRiderOrder = (orderId) => api.post(`/rider/orders/${orderId}/claim`).then(unwrap)
export const getRiderProfile = () => api.get('/rider/profile').then(unwrap)
export const getRiderInfo = () => api.get('/rider/info').then(unwrap)
export const updateRiderInfo = (payload) => api.put('/rider/info', payload).then(unwrap)
export const requestRiderServicePhoneChange = (payload) => api.post('/rider/info/service-phone-change', payload).then(unwrap)
export const getMyRiderApplication = () => api.get('/rider/application').then(unwrap)
export const setRiderOnline = (online) => api.patch('/rider/online', { online }).then(unwrap)
export const startAcceptingOrders = () => api.post('/rider/work/start').then(unwrap)
export const stopAcceptingOrders = () => api.post('/rider/work/end').then(unwrap)
export const listRiderTasks = (sort = 'SMART') => api.get('/rider/tasks', { params: { sort } }).then(unwrap)
export const claimRiderTask = (orderId) => api.post(`/rider/tasks/${orderId}/claim`).then(unwrap)
export const listRiderDeliveries = () => api.get('/rider/deliveries').then(unwrap)
export const getRiderOrderDetail = (orderId) => api.get(`/rider/deliveries/${orderId}/detail`).then(unwrap)
export const pickupRiderDelivery = (orderId) => api.post(`/rider/deliveries/${orderId}/pickup`).then(unwrap)
export const completeRiderDelivery = (orderId) => api.post(`/rider/deliveries/${orderId}/complete`).then(unwrap)
export const getDeliveryTracking = (orderId) => api.get(`/delivery/orders/${orderId}/tracking`).then(unwrap)
export const reportRiderLocation = (payload) => api.put('/rider/location', payload).then(unwrap)
export const getRiderOrderMessages = (orderId) => api.get(`/rider/deliveries/${orderId}/messages`).then(unwrap)
export const sendRiderOrderMessage = (orderId, content) => api.post(`/rider/deliveries/${orderId}/messages`, { content }).then(unwrap)
export const createRiderCallSession = (orderId) => api.post(`/rider/deliveries/${orderId}/call-session`).then(unwrap)
export const getRiderMerchantMessages = (orderId) => api.get(`/delivery/orders/${orderId}/merchant-messages`).then(unwrap)
export const sendRiderMerchantMessage = (orderId, content) => api.post(`/delivery/orders/${orderId}/merchant-messages`, { content }).then(unwrap)
export const listMyRiderWithdrawals = () => api.get('/rider/withdrawals').then(unwrap)
export const listMyRiderReviews = () => api.get('/rider/reviews').then(unwrap)
export const listMyRiderMetrics = () => api.get('/rider/metrics').then(unwrap)
export const listMyRiderSettlements = () => api.get('/rider/settlements').then(unwrap)
export const submitRiderApplication = (payload) => api.post('/rider/applications', payload).then(unwrap)
