apiVersion: v1
kind: ConfigMap
metadata:
  name: clas-config
  namespace: clas
data:
  MYSQL_DATABASE: clas
  MYSQL_HOST: clas-mysql
  MYSQL_PORT: "3306"
  REDIS_HOST: clas-redis
  REDIS_PORT: "6379"
  CORS_ALLOWED_ORIGINS: http://clas-frontend
