SELECT 'user' tbl, COUNT(*) cnt FROM user
UNION ALL SELECT 'merchant', COUNT(*) FROM merchant
UNION ALL SELECT 'product', COUNT(*) FROM product
UNION ALL SELECT 'orders', COUNT(*) FROM orders
UNION ALL SELECT 'order_item', COUNT(*) FROM order_item
UNION ALL SELECT 'cart', COUNT(*) FROM cart
UNION ALL SELECT 'review', COUNT(*) FROM review
UNION ALL SELECT 'review_reply', COUNT(*) FROM review_reply
UNION ALL SELECT 'review_vote', COUNT(*) FROM review_vote
UNION ALL SELECT 'favorite', COUNT(*) FROM favorite
UNION ALL SELECT 'notification', COUNT(*) FROM notification
UNION ALL SELECT 'deal_order', COUNT(*) FROM deal_order
UNION ALL SELECT 'group_deal', COUNT(*) FROM group_deal
UNION ALL SELECT 'service_booking', COUNT(*) FROM service_booking
UNION ALL SELECT 'payment', COUNT(*) FROM payment
UNION ALL SELECT 'user_address', COUNT(*) FROM user_address
UNION ALL SELECT 'user_penalty', COUNT(*) FROM user_penalty
UNION ALL SELECT 'appeal', COUNT(*) FROM appeal
UNION ALL SELECT 'announcement', COUNT(*) FROM announcement
UNION ALL SELECT 'chat_message', COUNT(*) FROM chat_message
UNION ALL SELECT 'merchant_audit_log', COUNT(*) FROM merchant_audit_log
UNION ALL SELECT 'user_coupon', COUNT(*) FROM user_coupon
UNION ALL SELECT 'coupon', COUNT(*) FROM coupon
UNION ALL SELECT 'user_bank_card', COUNT(*) FROM user_bank_card;
